export const INITIALIZE_PAGEDATA_REQUEST = 'platform/api/INITIALIZE_PAGEDATA_REQUEST';
export const RELOAD_PAGEDATA_REQUEST = 'platform/api/RELOAD_PAGEDATA_REQUEST';
export const LOAD_PAGEDATA_SUCCESS = 'platform/api/LOAD_PAGEDATA_SUCCESS';
export const LOAD_PAGEDATA_ERROR = 'platform/api/LOAD_PAGEDATA_ERROR';
export const SUBMIT_PAGEDATA_REQUEST = 'platform/api/SUBMIT_PAGEDATA_REQUEST';
export const SUBMIT_PAGEDATA_SUCCESS = 'platform/api/SUBMIT_PAGEDATA_SUCCESS';
export const SUBMIT_PAGEDATA_ERROR = 'platform/api/SUBMIT_PAGEDATA_ERROR';
